
-- 1. Tabla de Médicos
CREATE TABLE MEDICO (
    rut_medico VARCHAR2(12) NOT NULL PRIMARY KEY,
    nombre_completo VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(255) DEFAULT '123456'
);

-- 2. Tabla de Usuarios (Pacientes)
CREATE TABLE USUARIO (
    rut_paciente VARCHAR2(12) NOT NULL PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    nombre_completo VARCHAR2(100),
    telefono VARCHAR2(15),
    fecha_registro DATE DEFAULT SYSDATE
);

-- 3. Tabla de Administrador
-- Representa a la autoridad o gestión del centro médico
CREATE TABLE ADMINISTRADOR (
    rut_admin VARCHAR2(12) NOT NULL PRIMARY KEY,
    nombre_completo VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    cargo VARCHAR2(50) DEFAULT 'Administrativo' -- Ej: Director, Secretaria, IT
);

-- 4. Tabla de Citas
CREATE TABLE CITA (
    id_cita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut_medico VARCHAR2(12) NOT NULL,
    rut_paciente VARCHAR2(12),
    fecha_hora TIMESTAMP NOT NULL,
    estado VARCHAR2(20) DEFAULT 'DISPONIBLE',
    
    CONSTRAINT fk_cita_medico FOREIGN KEY (rut_medico) REFERENCES MEDICO(rut_medico),
    CONSTRAINT fk_cita_usuario FOREIGN KEY (rut_paciente) REFERENCES USUARIO(rut_paciente)
);



-- DATOS DE PRUEBA 

-- 1. Médicos
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('11111111-1', 'Dr. Juan Pérez', 'Cardiología');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('22222222-2', 'Dra. Ana López', 'Geriatría');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('33333333-3', 'Dr. Roberto Diaz', 'Medicina General');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('44444444-4', 'Dra. Elena Salas', 'Pediatría');

-- 2. Paciente de Prueba
INSERT INTO USUARIO (rut_paciente, email, password_hash, nombre_completo, telefono)
VALUES ('99999999-9', 'kevin@gmail.com', '123456', 'Kevin García', '+56972254112');

-- 3. Administrador
INSERT INTO ADMINISTRADOR (rut_admin, nombre_completo, email, password_hash, cargo)
VALUES ('55555555-5', 'Antonio Silva', 'antonioS@vitalsync.cl', 'admin123', 'Director Médico');

-- 4. Citas (Agenda Martes 09/12/2025)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('11111111-1', TO_TIMESTAMP('2025-12-09 13:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE'); 

INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('33333333-3', TO_TIMESTAMP('2025-12-09 14:30', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE');

INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('22222222-2', TO_TIMESTAMP('2025-12-09 15:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE'); 

INSERT INTO CITA (rut_medico, fecha_hora, estado) --Miercoles 10/12/2025
VALUES ('44444444-4', TO_TIMESTAMP('2025-12-10 17:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE');

-- Cita Reservada
INSERT INTO CITA (rut_medico, rut_paciente, fecha_hora, estado) 
VALUES ('33333333-3', '99999999-9', TO_TIMESTAMP('2025-12-09 16:00', 'YYYY-MM-DD HH24:MI'), 'RESERVADA');

COMMIT;