

-- 1. Tabla de Médicos
CREATE TABLE MEDICO (
    rut_medico VARCHAR2(12) NOT NULL PRIMARY KEY,
    nombre_completo VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(255) DEFAULT '123456'
);

-- 2. Tabla de Usuarios
CREATE TABLE USUARIO (
    rut_paciente VARCHAR2(12) NOT NULL PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    nombre_completo VARCHAR2(100),
    telefono VARCHAR2(15),
    fecha_registro DATE DEFAULT SYSDATE
);

-- 3. Tabla de Citas
CREATE TABLE CITA (
    id_cita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut_medico VARCHAR2(12) NOT NULL,
    rut_paciente VARCHAR2(12),
    fecha_hora TIMESTAMP NOT NULL,
    estado VARCHAR2(20) DEFAULT 'DISPONIBLE',
    
    CONSTRAINT fk_cita_medico FOREIGN KEY (rut_medico) REFERENCES MEDICO(rut_medico),
    CONSTRAINT fk_cita_usuario FOREIGN KEY (rut_paciente) REFERENCES USUARIO(rut_paciente)
);

-- =============================================
-- DATOS DE PRUEBA 
-- =============================================

-- 1. Médicos
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('11111111-1', 'Dr. Juan Pérez', 'Cardiología');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('22222222-2', 'Dra. Ana López', 'Geriatría');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('33333333-3', 'Dr. Roberto Diaz', 'Medicina General');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('44444444-4', 'Dra. Elena Salas', 'Pediatría');
INSERT INTO MEDICO (rut_medico, nombre_completo, especialidad) VALUES ('55555555-5', 'Dr. Diego Guerrero', 'Medicina General');

-- 2. Paciente de Prueba
INSERT INTO USUARIO (rut_paciente, email, password_hash, nombre_completo, telefono)
VALUES ('99999999-9', 'cristian@gmail.com', '123456', 'Cristian Carvajal', '+56943211234');

-- 3. CITAS 

-- Cita 1: Jueves 04 a las 09:30 AM (Disponible - Cardiología)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('11111111-1', TO_TIMESTAMP('2025-12-04 09:30', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE'); 

-- Cita 2: Jueves 04 a las 10:30 AM (Disponible - Medicina General)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('33333333-3', TO_TIMESTAMP('2025-12-04 10:30', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE');

-- Cita 3: Jueves 04 a las 11:00 AM (Disponible - Geriatría)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('22222222-2', TO_TIMESTAMP('2025-12-04 11:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE'); 

-- Cita 4: Viernes 05 a las 15:00 PM (Disponible - Pediatría)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('44444444-4', TO_TIMESTAMP('2025-12-05 15:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE');
-- Cita 5: Sábado 06 a las 12:00 PM (Disponible - Medicina General)
INSERT INTO CITA (rut_medico, fecha_hora, estado) 
VALUES ('55555555-5', TO_TIMESTAMP('2025-12-06 12:00', 'YYYY-MM-DD HH24:MI'), 'DISPONIBLE');

-- 4. Cita PRE-RESERVADA (Para probar cancelación)
-- Jueves 04 a las 16:00 PM (Asignada al Paciente Demo)
INSERT INTO CITA (rut_medico, rut_paciente, fecha_hora, estado) 
VALUES ('33333333-3', '99999999-9', TO_TIMESTAMP('2025-12-04 16:00', 'YYYY-MM-DD HH24:MI'), 'RESERVADA');

COMMIT;